"""Writes reference Marian token ids produced by Hugging Face transformers.

The OfflineCli `parity` command compares them with the C# tokenizer.

Usage:
    python marian_parity.py <models-dir> <out.json> <model-id> [<model-id> ...] [--csharp <file.cs>]

--csharp also writes a subset as C# test data (tests/Translator.Tests/Offline/MarianParityData.cs).

Requirements (no torch needed): pip install transformers sentencepiece
"""

import json
import os
import sys

from transformers import MarianTokenizer

TEXTS = [
    "Hello, world!",
    "The quick brown fox jumps over the lazy dog.",
    "  Leading and trailing spaces  ",
    "Multiple   spaces\tand\ttabs",
    "Line one\nLine two\r\nLine three\n\nNew paragraph",
    "Numbers: 3.14159, 1,000,000 and 42% of $19.99 on 2026-09-14",
    "Emoji 😀👍🏽🇺🇦 and symbols ©®™ ✓ ★",
    "MiXeD CaSe TeXt and ALLCAPS WORDS",
    "\"Double quotes\" and 'single quotes', «guillemets», „German“ and “curly”",
    "Привет, как дела? Всё хорошо, спасибо!",
    "Grüße aus München! Straße, Äpfel, Öl.",
    "안녕하세요, 만나서 반갑습니다.",
    "日本語のテキストです。ｶﾀｶﾅ",
    "中文文本，测试一下。",
    "Full-width ＡＢＣ１２３ and ligature ﬁ and ½ ⅓",
    "Dashes — – - and ellipsis… and non-breaking space",
    "e-mail: test@example.com, URL: https://example.com/a?b=c&d=e#frag",
    "zero​width and soft­hyphen and bell",
    "Çok güzel, teşekkür ederim. İyi günler!",
    "¿Qué tal? ¡Muy bien! São Paulo, coração.",
    "",
    "a</s>b <unk> c<pad>",
    ">>fra<< text that starts with a language code",
    "Ünïcödé ÅÉÎÕÜ ñ and ÿ",
    "Tabs\tand　ideographic space",
    "C'est l'été, n'est-ce pas? Don't stop!",
    "Ukrainian: Добрий день! Як справи? Їжак, ґанок, єдність.",
    "(Parentheses) [brackets] {braces} <angle> #hash @at ^caret ~tilde",
]

TARGET_TOKEN_TEXT = "How are you today?"
PREFERRED_CODES = (">>tur<<", ">>jpn<<", ">>pt<<", ">>pt_BR<<", ">>cmn_Hans<<")


CSHARP_TEXTS = {0, 2, 4, 5, 6, 8, 9, 10, 14, 15, 17, 21}


def write_csharp(cases, texts, path: str) -> None:
    lines = [
        "// <auto-generated> by tools/OfflineCli/scripts/marian_parity.py (transformers MarianTokenizer) </auto-generated>",
        "#nullable enable",
        "namespace Translator.Tests.Offline;",
        "",
        "internal static class MarianParityData",
        "{",
        "    public static readonly (string Model, string Text, string? TargetToken, int[] Ids)[] Cases =",
        "    [",
    ]
    selected = {texts[i] for i in CSHARP_TEXTS}
    for case in cases:
        if case["text"] not in selected and "target_token" not in case:
            continue
        token = json.dumps(case["target_token"]) if "target_token" in case else "null"
        ids = ", ".join(str(i) for i in case["ids"])
        text = json.dumps(case["text"], ensure_ascii=False)
        lines.append(f'        ("{case["model"]}", {text}, {token}, [{ids}]),')
    lines += ["    ];", "}", ""]
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


def main() -> None:
    args = sys.argv[1:]
    csharp_path = None
    if "--csharp" in args:
        index = args.index("--csharp")
        csharp_path = args[index + 1]
        del args[index : index + 2]
    models_dir, out_path, model_ids = args[0], args[1], args[2:]
    cases = []
    for model_id in model_ids:
        tokenizer = MarianTokenizer.from_pretrained(os.path.join(models_dir, model_id))
        for text in TEXTS:
            cases.append({"model": model_id, "text": text, "ids": tokenizer(text)["input_ids"]})
        for code in [c for c in PREFERRED_CODES if c in tokenizer.supported_language_codes]:
            ids = tokenizer(code + " " + TARGET_TOKEN_TEXT)["input_ids"]
            cases.append({"model": model_id, "text": TARGET_TOKEN_TEXT, "target_token": code, "ids": ids})
    with open(out_path, "w", encoding="utf-8") as handle:
        json.dump(cases, handle, ensure_ascii=False, indent=1)
    print(f"{len(cases)} cases written to {out_path}")
    if csharp_path:
        write_csharp(cases, TEXTS, csharp_path)
        print(f"C# test data written to {csharp_path}")


if __name__ == "__main__":
    main()
